# frozen_string_literal: true

# Automated follow-up system: a kanban-aware re-engagement engine.
#
# Rules are bound to a pipeline stage. When a pipeline item lands on that
# stage, an execution is scheduled. At each `next_attempt_at` the job sends
# a re-engagement message (generated by AI or a static template). The exec
# is cancelled when the lead replies, the assigned agent replies, or the
# pipeline item moves to a different stage. After the last attempt the rule
# can optionally move the item to a "disqualified" stage.
class CreateFollowUps < ActiveRecord::Migration[7.1]
  def change
    create_table :follow_up_rules, id: :uuid, default: -> { 'gen_random_uuid()' } do |t|
      t.uuid   :account_id,        null: false
      t.string :name,              null: false
      t.uuid   :pipeline_stage_id, null: false

      # Array of delays in seconds from the previous attempt (or from rule
      # trigger for the first one). Example default: [3600, 43200, 64800] →
      # 1h, 12h, 18h. Length of the array = max number of attempts.
      t.jsonb :intervals, null: false, default: [3600, 43200, 64800]

      # How the follow-up message is produced.
      # - inbox_agent  : reuse the agent already answering on the inbox
      # - custom_agent : use the agent_bot referenced by custom_agent_bot_id
      # - template     : send template_text as-is (with {{name}}/{{...}} vars)
      t.string :message_source, null: false, default: 'inbox_agent'
      t.uuid   :custom_agent_bot_id
      t.text   :template_text
      t.text   :extra_instructions

      # After the last attempt with no response, what to do with the pipeline
      # item: 'noop' = leave it alone, 'move_to_stage' = move to target.
      t.string :on_max_attempts_action, null: false, default: 'noop'
      t.uuid   :on_max_target_stage_id

      t.boolean  :enabled, null: false, default: true
      t.datetime :created_at, null: false, default: -> { 'now()' }
      t.datetime :updated_at, null: false, default: -> { 'now()' }
    end

    add_foreign_key :follow_up_rules, :accounts,        column: :account_id,            on_delete: :cascade
    add_foreign_key :follow_up_rules, :pipeline_stages, column: :pipeline_stage_id,     on_delete: :cascade
    add_foreign_key :follow_up_rules, :pipeline_stages, column: :on_max_target_stage_id, on_delete: :nullify
    add_foreign_key :follow_up_rules, :agent_bots,      column: :custom_agent_bot_id,   on_delete: :nullify

    add_index :follow_up_rules, :account_id
    add_index :follow_up_rules, %i[account_id pipeline_stage_id enabled], name: 'idx_follow_up_rules_trigger'

    create_table :follow_up_executions, id: :uuid, default: -> { 'gen_random_uuid()' } do |t|
      t.uuid :account_id,     null: false
      t.uuid :rule_id,        null: false
      t.uuid :conversation_id, null: false

      # Append-only log of attempt timestamps. attempts_at.size tracks progress.
      t.jsonb :attempts_at, null: false, default: []

      t.datetime :next_attempt_at, null: false

      # pending → done (finished all attempts) | cancelled (interrupted early)
      t.string :status,        null: false, default: 'pending'
      t.string :cancel_reason

      t.datetime :created_at, null: false, default: -> { 'now()' }
      t.datetime :updated_at, null: false, default: -> { 'now()' }
    end

    add_foreign_key :follow_up_executions, :accounts,           column: :account_id,      on_delete: :cascade
    add_foreign_key :follow_up_executions, :follow_up_rules,    column: :rule_id,         on_delete: :cascade
    add_foreign_key :follow_up_executions, :conversations,      column: :conversation_id, on_delete: :cascade

    # Hot path: the job selects pending executions whose next_attempt_at <= now.
    add_index :follow_up_executions, %i[status next_attempt_at], name: 'idx_follow_up_executions_runnable'
    # Cancel lookups by conversation (when a message arrives) and by rule.
    add_index :follow_up_executions, %i[conversation_id status], name: 'idx_follow_up_executions_by_conv'
    add_index :follow_up_executions, :rule_id
    add_index :follow_up_executions, :account_id
  end
end
